INCLUDE Syscall.inc

ScCode SEGMENT PARA READ EXECUTE ALIAS(".ScCode")

$SYSCALL ScAcceptConnectPort, 6
$SYSCALL ScAccessCheck, 8
$SYSCALL ScAccessCheckAndAuditAlarm, 11
$SYSCALL ScAccessCheckByType, 11
$SYSCALL ScAccessCheckByTypeAndAuditAlarm, 16
$SYSCALL ScAccessCheckByTypeResultList, 11
$SYSCALL ScAccessCheckByTypeResultListAndAuditAlarm, 16
$SYSCALL ScAccessCheckByTypeResultListAndAuditAlarmByHandle, 17
$SYSCALL ScAcquireCrossVmMutant, 2
$SYSCALL ScAcquireProcessActivityReference, 3
$SYSCALL ScAddAtom, 3
$SYSCALL ScAddAtomEx, 4
$SYSCALL ScAddBootEntry, 2
$SYSCALL ScAddDriverEntry, 2
$SYSCALL ScAdjustGroupsToken, 6
$SYSCALL ScAdjustPrivilegesToken, 6
$SYSCALL ScAdjustTokenClaimsAndDeviceGroups, 16
$SYSCALL ScAlertResumeThread, 2
$SYSCALL ScAlertThread, 1
$SYSCALL ScAlertThreadByThreadId, 1
$SYSCALL ScAlertThreadByThreadIdEx, 2
$SYSCALL ScAllocateLocallyUniqueId, 1
$SYSCALL ScAllocateReserveObject, 3
$SYSCALL ScAllocateUserPhysicalPages, 3
$SYSCALL ScAllocateUserPhysicalPagesEx, 5
$SYSCALL ScAllocateUuids, 4
$SYSCALL ScAllocateVirtualMemory, 6
$SYSCALL ScAllocateVirtualMemoryEx, 7
$SYSCALL ScAlpcAcceptConnectPort, 9
$SYSCALL ScAlpcCancelMessage, 3
$SYSCALL ScAlpcConnectPort, 11
$SYSCALL ScAlpcConnectPortEx, 11
$SYSCALL ScAlpcCreatePort, 3
$SYSCALL ScAlpcCreatePortSection, 6
$SYSCALL ScAlpcCreateResourceReserve, 4
$SYSCALL ScAlpcCreateSectionView, 3
$SYSCALL ScAlpcCreateSecurityContext, 3
$SYSCALL ScAlpcDeletePortSection, 3
$SYSCALL ScAlpcDeleteResourceReserve, 3
$SYSCALL ScAlpcDeleteSectionView, 3
$SYSCALL ScAlpcDeleteSecurityContext, 3
$SYSCALL ScAlpcDisconnectPort, 2
$SYSCALL ScAlpcImpersonateClientContainerOfPort, 3
$SYSCALL ScAlpcImpersonateClientOfPort, 3
$SYSCALL ScAlpcOpenSenderProcess, 6
$SYSCALL ScAlpcOpenSenderThread, 6
$SYSCALL ScAlpcQueryInformation, 5
$SYSCALL ScAlpcQueryInformationMessage, 6
$SYSCALL ScAlpcRevokeSecurityContext, 3
$SYSCALL ScAlpcSendWaitReceivePort, 8
$SYSCALL ScAlpcSetInformation, 4
$SYSCALL ScApphelpCacheControl, 2
$SYSCALL ScAreMappedFilesTheSame, 2
$SYSCALL ScAssignProcessToJobObject, 2
$SYSCALL ScAssociateWaitCompletionPacket, 8
$SYSCALL ScCallbackReturn, 3
$SYSCALL ScCallEnclave, 4
$SYSCALL ScCancelIoFile, 2
$SYSCALL ScCancelIoFileEx, 3
$SYSCALL ScCancelSynchronousIoFile, 3
$SYSCALL ScCancelTimer, 2
$SYSCALL ScCancelTimer2, 2
$SYSCALL ScCancelWaitCompletionPacket, 2
$SYSCALL ScChangeProcessState, 6
$SYSCALL ScChangeThreadState, 6
$SYSCALL ScClearEvent, 1
$SYSCALL ScClose, 1
$SYSCALL ScCloseObjectAuditAlarm, 3
$SYSCALL ScCommitComplete, 2
$SYSCALL ScCommitEnlistment, 2
$SYSCALL ScCommitRegistryTransaction, 2
$SYSCALL ScCommitTransaction, 2
$SYSCALL ScCompactKeys, 2
$SYSCALL ScCompareObjects, 2
$SYSCALL ScCompareSigningLevels, 2
$SYSCALL ScCompareTokens, 3
$SYSCALL ScCompleteConnectPort, 1
$SYSCALL ScCompressKey, 1
$SYSCALL ScConnectPort, 8
$SYSCALL ScContinue, 2
$SYSCALL ScContinueEx, 2
$SYSCALL ScConvertBetweenAuxiliaryCounterAndPerformanceCounter, 4
$SYSCALL ScCopyFileChunk, 10
$SYSCALL ScCreateCrossVmEvent, 6
$SYSCALL ScCreateCrossVmMutant, 6
$SYSCALL ScCreateDebugObject, 4
$SYSCALL ScCreateDirectoryObject, 3
$SYSCALL ScCreateDirectoryObjectEx, 5
$SYSCALL ScCreateEnclave, 9
$SYSCALL ScCreateEnlistment, 8
$SYSCALL ScCreateEvent, 5
$SYSCALL ScCreateEventPair, 3
$SYSCALL ScCreateFile, 11
$SYSCALL ScCreateIoCompletion, 4
$SYSCALL ScCreateIoRing, 5
$SYSCALL ScCreateIRTimer, 3
$SYSCALL ScCreateJobObject, 3
$SYSCALL ScCreateJobSet, 3
$SYSCALL ScCreateKey, 7
$SYSCALL ScCreateKeyedEvent, 4
$SYSCALL ScCreateKeyTransacted, 8
$SYSCALL ScCreateLowBoxToken, 9
$SYSCALL ScCreateMailslotFile, 8
$SYSCALL ScCreateMutant, 4
$SYSCALL ScCreateNamedPipeFile, 14
$SYSCALL ScCreatePagingFile, 4
$SYSCALL ScCreatePartition, 5
$SYSCALL ScCreatePort, 5
$SYSCALL ScCreatePrivateNamespace, 4
$SYSCALL ScCreateProcess, 8
$SYSCALL ScCreateProcessEx, 9
$SYSCALL ScCreateProcessStateChange, 5
$SYSCALL ScCreateProfile, 9
$SYSCALL ScCreateProfileEx, 10
$SYSCALL ScCreateRegistryTransaction, 4
$SYSCALL ScCreateResourceManager, 7
$SYSCALL ScCreateSection, 7
$SYSCALL ScCreateSectionEx, 9
$SYSCALL ScCreateSemaphore, 5
$SYSCALL ScCreateSymbolicLinkObject, 4
$SYSCALL ScCreateThread, 8
$SYSCALL ScCreateThreadEx, 11
$SYSCALL ScCreateThreadStateChange, 5
$SYSCALL ScCreateTimer, 4
$SYSCALL ScCreateTimer2, 5
$SYSCALL ScCreateToken, 13
$SYSCALL ScCreateTokenEx, 17
$SYSCALL ScCreateTransaction, 10
$SYSCALL ScCreateTransactionManager, 6
$SYSCALL ScCreateUserProcess, 11
$SYSCALL ScCreateWaitablePort, 5
$SYSCALL ScCreateWaitCompletionPacket, 3
$SYSCALL ScCreateWnfStateName, 7
$SYSCALL ScCreateWorkerFactory, 10
$SYSCALL ScDebugActiveProcess, 2
$SYSCALL ScDebugContinue, 3
$SYSCALL ScDelayExecution, 2
$SYSCALL ScDeleteAtom, 1
$SYSCALL ScDeleteBootEntry, 1
$SYSCALL ScDeleteDriverEntry, 1
$SYSCALL ScDeleteFile, 1
$SYSCALL ScDeleteKey, 1
$SYSCALL ScDeleteObjectAuditAlarm, 3
$SYSCALL ScDeletePrivateNamespace, 1
$SYSCALL ScDeleteValueKey, 2
$SYSCALL ScDeleteWnfStateData, 2
$SYSCALL ScDeleteWnfStateName, 1
$SYSCALL ScDeviceIoControlFile, 10
$SYSCALL ScDisableLastKnownGood, 0
$SYSCALL ScDisplayString, 1
$SYSCALL ScDrawText, 1
$SYSCALL ScDuplicateObject, 7
$SYSCALL ScDuplicateToken, 6
$SYSCALL ScEnableLastKnownGood, 0
$SYSCALL ScEnumerateBootEntries, 2
$SYSCALL ScEnumerateDriverEntries, 2
$SYSCALL ScEnumerateKey, 6
$SYSCALL ScEnumerateSystemEnvironmentValuesEx, 3
$SYSCALL ScEnumerateTransactionObject, 5
$SYSCALL ScEnumerateValueKey, 6
$SYSCALL ScExtendSection, 2
$SYSCALL ScFilterBootOption, 5
$SYSCALL ScFilterToken, 6
$SYSCALL ScFilterTokenEx, 14
$SYSCALL ScFindAtom, 3
$SYSCALL ScFlushBuffersFile, 2
$SYSCALL ScFlushBuffersFileEx, 5
$SYSCALL ScFlushInstallUILanguage, 2
$SYSCALL ScFlushInstructionCache, 3
$SYSCALL ScFlushKey, 1
$SYSCALL ScFlushProcessWriteBuffers, 0
$SYSCALL ScFlushVirtualMemory, 4
$SYSCALL ScFlushWriteBuffer, 0
$SYSCALL ScFreeUserPhysicalPages, 3
$SYSCALL ScFreeVirtualMemory, 4
$SYSCALL ScFreezeRegistry, 1
$SYSCALL ScFreezeTransactions, 2
$SYSCALL ScFsControlFile, 10
$SYSCALL ScGetCachedSigningLevel, 6
$SYSCALL ScGetCompleteWnfStateSubscription, 6
$SYSCALL ScGetContextThread, 2
$SYSCALL ScGetCurrentProcessorNumber, 0
$SYSCALL ScGetCurrentProcessorNumberEx, 1
$SYSCALL ScGetDevicePowerState, 2
$SYSCALL ScGetMUIRegistryInfo, 3
$SYSCALL ScGetNextProcess, 5
$SYSCALL ScGetNextThread, 6
$SYSCALL ScGetNlsSectionPtr, 5
$SYSCALL ScGetNotificationResourceManager, 7
$SYSCALL ScGetPlugPlayEvent, 4
$SYSCALL ScGetWriteWatch, 7
$SYSCALL ScImpersonateAnonymousToken, 1
$SYSCALL ScImpersonateClientOfPort, 2
$SYSCALL ScImpersonateThread, 3
$SYSCALL ScInitializeEnclave, 5
$SYSCALL ScInitializeNlsFiles, 4
$SYSCALL ScInitializeRegistry, 1
$SYSCALL ScInitiatePowerAction, 4
$SYSCALL ScIsProcessInJob, 2
$SYSCALL ScIsSystemResumeAutomatic, 0
$SYSCALL ScIsUILanguageComitted, 0
$SYSCALL ScListenPort, 2
$SYSCALL ScLoadDriver, 1
$SYSCALL ScLoadEnclaveData, 9
$SYSCALL ScLoadKey, 2
$SYSCALL ScLoadKey2, 3
$SYSCALL ScLoadKey3, 8
$SYSCALL ScLoadKeyEx, 8
$SYSCALL ScLockFile, 10
$SYSCALL ScLockProductActivationKeys, 2
$SYSCALL ScLockRegistryKey, 1
$SYSCALL ScLockVirtualMemory, 4
$SYSCALL ScMakePermanentObject, 1
$SYSCALL ScMakeTemporaryObject, 1
$SYSCALL ScManagePartition, 5
$SYSCALL ScMapCMFModule, 6
$SYSCALL ScMapUserPhysicalPages, 3
$SYSCALL ScMapUserPhysicalPagesScatter, 3
$SYSCALL ScMapViewOfSection, 10
$SYSCALL ScMapViewOfSectionEx, 9
$SYSCALL ScModifyBootEntry, 1
$SYSCALL ScModifyDriverEntry, 1
$SYSCALL ScNotifyChangeDirectoryFile, 9
$SYSCALL ScNotifyChangeDirectoryFileEx, 10
$SYSCALL ScNotifyChangeKey, 10
$SYSCALL ScNotifyChangeMultipleKeys, 12
$SYSCALL ScNotifyChangeSession, 8
$SYSCALL ScOpenDirectoryObject, 3
$SYSCALL ScOpenEnlistment, 5
$SYSCALL ScOpenEvent, 3
$SYSCALL ScOpenEventPair, 3
$SYSCALL ScOpenFile, 6
$SYSCALL ScOpenIoCompletion, 3
$SYSCALL ScOpenJobObject, 3
$SYSCALL ScOpenKey, 3
$SYSCALL ScOpenKeyedEvent, 3
$SYSCALL ScOpenKeyEx, 4
$SYSCALL ScOpenKeyTransacted, 4
$SYSCALL ScOpenKeyTransactedEx, 5
$SYSCALL ScOpenMutant, 3
$SYSCALL ScOpenObjectAuditAlarm, 12
$SYSCALL ScOpenPartition, 3
$SYSCALL ScOpenPrivateNamespace, 4
$SYSCALL ScOpenProcess, 4
$SYSCALL ScOpenProcessToken, 3
$SYSCALL ScOpenProcessTokenEx, 4
$SYSCALL ScOpenRegistryTransaction, 3
$SYSCALL ScOpenResourceManager, 5
$SYSCALL ScOpenSection, 3
$SYSCALL ScOpenSemaphore, 3
$SYSCALL ScOpenSession, 3
$SYSCALL ScOpenSymbolicLinkObject, 3
$SYSCALL ScOpenThread, 4
$SYSCALL ScOpenThreadToken, 4
$SYSCALL ScOpenThreadTokenEx, 5
$SYSCALL ScOpenTimer, 3
$SYSCALL ScOpenTransaction, 5
$SYSCALL ScOpenTransactionManager, 6
$SYSCALL ScPlugPlayControl, 3
$SYSCALL ScPowerInformation, 5
$SYSCALL ScPrepareComplete, 2
$SYSCALL ScPrepareEnlistment, 2
$SYSCALL ScPrePrepareComplete, 2
$SYSCALL ScPrePrepareEnlistment, 2
$SYSCALL ScPrivilegeCheck, 3
$SYSCALL ScPrivilegedServiceAuditAlarm, 5
$SYSCALL ScPrivilegeObjectAuditAlarm, 6
$SYSCALL ScPropagationComplete, 4
$SYSCALL ScPropagationFailed, 3
$SYSCALL ScProtectVirtualMemory, 5
$SYSCALL ScPssCaptureVaSpaceBulk, 5
$SYSCALL ScPulseEvent, 2
$SYSCALL ScQueryAttributesFile, 2
$SYSCALL ScQueryAuxiliaryCounterFrequency, 1
$SYSCALL ScQueryBootEntryOrder, 2
$SYSCALL ScQueryBootOptions, 2
$SYSCALL ScQueryDebugFilterState, 2
$SYSCALL ScQueryDefaultLocale, 2
$SYSCALL ScQueryDefaultUILanguage, 1
$SYSCALL ScQueryDirectoryFile, 11
$SYSCALL ScQueryDirectoryFileEx, 10
$SYSCALL ScQueryDirectoryObject, 7
$SYSCALL ScQueryDriverEntryOrder, 2
$SYSCALL ScQueryEaFile, 9
$SYSCALL ScQueryEvent, 5
$SYSCALL ScQueryFullAttributesFile, 2
$SYSCALL ScQueryInformationAtom, 5
$SYSCALL ScQueryInformationByName, 5
$SYSCALL ScQueryInformationCpuPartition, 5
$SYSCALL ScQueryInformationEnlistment, 5
$SYSCALL ScQueryInformationFile, 5
$SYSCALL ScQueryInformationJobObject, 5
$SYSCALL ScQueryInformationPort, 5
$SYSCALL ScQueryInformationProcess, 5
$SYSCALL ScQueryInformationResourceManager, 5
$SYSCALL ScQueryInformationThread, 5
$SYSCALL ScQueryInformationToken, 5
$SYSCALL ScQueryInformationTransaction, 5
$SYSCALL ScQueryInformationTransactionManager, 5
$SYSCALL ScQueryInformationWorkerFactory, 5
$SYSCALL ScQueryInstallUILanguage, 1
$SYSCALL ScQueryIntervalProfile, 2
$SYSCALL ScQueryIoCompletion, 5
$SYSCALL ScQueryIoRingCapabilities, 2
$SYSCALL ScQueryKey, 5
$SYSCALL ScQueryLicenseValue, 5
$SYSCALL ScQueryMultipleValueKey, 6
$SYSCALL ScQueryMutant, 5
$SYSCALL ScQueryObject, 5
$SYSCALL ScQueryOpenSubKeys, 2
$SYSCALL ScQueryOpenSubKeysEx, 4
$SYSCALL ScQueryPerformanceCounter, 2
$SYSCALL ScQueryPortInformationProcess, 0
$SYSCALL ScQueryQuotaInformationFile, 9
$SYSCALL ScQuerySection, 5
$SYSCALL ScQuerySecurityAttributesToken, 6
$SYSCALL ScQuerySecurityObject, 5
$SYSCALL ScQuerySecurityPolicy, 6
$SYSCALL ScQuerySemaphore, 5
$SYSCALL ScQuerySymbolicLinkObject, 3
$SYSCALL ScQuerySystemEnvironmentValue, 4
$SYSCALL ScQuerySystemEnvironmentValueEx, 5
$SYSCALL ScQuerySystemInformation, 4
$SYSCALL ScQuerySystemInformationEx, 6
$SYSCALL ScQuerySystemTime, 1
$SYSCALL ScQueryTimer, 5
$SYSCALL ScQueryTimerResolution, 3
$SYSCALL ScQueryValueKey, 6
$SYSCALL ScQueryVirtualMemory, 6
$SYSCALL ScQueryVolumeInformationFile, 5
$SYSCALL ScQueryWnfStateData, 6
$SYSCALL ScQueryWnfStateNameInformation, 5
$SYSCALL ScQueueApcThread, 5
$SYSCALL ScQueueApcThreadEx, 6
$SYSCALL ScQueueApcThreadEx2, 7
$SYSCALL ScRaiseException, 3
$SYSCALL ScRaiseHardError, 6
$SYSCALL ScReadFile, 9
$SYSCALL ScReadFileScatter, 9
$SYSCALL ScReadOnlyEnlistment, 2
$SYSCALL ScReadRequestData, 6
$SYSCALL ScReadVirtualMemory, 5
$SYSCALL ScReadVirtualMemoryEx, 6
$SYSCALL ScRecoverEnlistment, 2
$SYSCALL ScRecoverResourceManager, 1
$SYSCALL ScRecoverTransactionManager, 1
$SYSCALL ScRegisterProtocolAddressInformation, 5
$SYSCALL ScRegisterThreadTerminatePort, 1
$SYSCALL ScReleaseKeyedEvent, 4
$SYSCALL ScReleaseMutant, 2
$SYSCALL ScReleaseSemaphore, 3
$SYSCALL ScReleaseWorkerFactoryWorker, 1
$SYSCALL ScRemoveIoCompletion, 5
$SYSCALL ScRemoveIoCompletionEx, 6
$SYSCALL ScRemoveProcessDebug, 2
$SYSCALL ScRenameKey, 2
$SYSCALL ScRenameTransactionManager, 2
$SYSCALL ScReplaceKey, 3
$SYSCALL ScReplacePartitionUnit, 3
$SYSCALL ScReplyPort, 2
$SYSCALL ScReplyWaitReceivePort, 4
$SYSCALL ScReplyWaitReceivePortEx, 5
$SYSCALL ScReplyWaitReplyPort, 2
$SYSCALL ScRequestPort, 2
$SYSCALL ScRequestWaitReplyPort, 3
$SYSCALL ScResetEvent, 2
$SYSCALL ScResetWriteWatch, 3
$SYSCALL ScRestoreKey, 3
$SYSCALL ScResumeProcess, 1
$SYSCALL ScResumeThread, 2
$SYSCALL ScRevertContainerImpersonation, 0
$SYSCALL ScRollbackComplete, 2
$SYSCALL ScRollbackEnlistment, 2
$SYSCALL ScRollbackRegistryTransaction, 2
$SYSCALL ScRollbackTransaction, 2
$SYSCALL ScRollforwardTransactionManager, 2
$SYSCALL ScSaveKey, 2
$SYSCALL ScSaveKeyEx, 3
$SYSCALL ScSaveMergedKeys, 3
$SYSCALL ScSecureConnectPort, 9
$SYSCALL ScSerializeBoot, 0
$SYSCALL ScSetBootEntryOrder, 2
$SYSCALL ScSetBootOptions, 2
$SYSCALL ScSetCachedSigningLevel, 5
$SYSCALL ScSetCachedSigningLevel2, 6
$SYSCALL ScSetContextThread, 2
$SYSCALL ScSetDebugFilterState, 3
$SYSCALL ScSetDefaultHardErrorPort, 1
$SYSCALL ScSetDefaultLocale, 2
$SYSCALL ScSetDefaultUILanguage, 1
$SYSCALL ScSetDriverEntryOrder, 2
$SYSCALL ScSetEaFile, 4
$SYSCALL ScSetEvent, 2
$SYSCALL ScSetEventEx, 2
$SYSCALL ScSetEventBoostPriority, 1
$SYSCALL ScSetHighEventPair, 1
$SYSCALL ScSetHighWaitLowEventPair, 1
$SYSCALL ScSetInformationDebugObject, 5
$SYSCALL ScSetInformationEnlistment, 4
$SYSCALL ScSetInformationFile, 5
$SYSCALL ScSetInformationIoRing, 4
$SYSCALL ScSetInformationJobObject, 4
$SYSCALL ScSetInformationKey, 4
$SYSCALL ScSetInformationObject, 4
$SYSCALL ScSetInformationProcess, 4
$SYSCALL ScSetInformationResourceManager, 4
$SYSCALL ScSetInformationSymbolicLink, 4
$SYSCALL ScSetInformationThread, 4
$SYSCALL ScSetInformationToken, 4
$SYSCALL ScSetInformationTransaction, 4
$SYSCALL ScSetInformationTransactionManager, 4
$SYSCALL ScSetInformationVirtualMemory, 6
$SYSCALL ScSetInformationWorkerFactory, 4
$SYSCALL ScSetIntervalProfile, 2
$SYSCALL ScSetIoCompletion, 5
$SYSCALL ScSetIoCompletionEx, 6
$SYSCALL ScSetIRTimer, 2
$SYSCALL ScSetLdtEntries, 6
$SYSCALL ScSetLowEventPair, 1
$SYSCALL ScSetLowWaitHighEventPair, 1
$SYSCALL ScSetQuotaInformationFile, 4
$SYSCALL ScSetSecurityObject, 3
$SYSCALL ScSetSystemEnvironmentValue, 2
$SYSCALL ScSetSystemEnvironmentValueEx, 5
$SYSCALL ScSetSystemInformation, 3
$SYSCALL ScSetSystemPowerState, 3
$SYSCALL ScSetSystemTime, 2
$SYSCALL ScSetThreadExecutionState, 2
$SYSCALL ScSetTimer, 7
$SYSCALL ScSetTimer2, 4
$SYSCALL ScSetTimerEx, 4
$SYSCALL ScSetTimerResolution, 3
$SYSCALL ScSetUuidSeed, 1
$SYSCALL ScSetValueKey, 6
$SYSCALL ScSetVolumeInformationFile, 5
$SYSCALL ScSetWnfProcessNotificationEvent, 1
$SYSCALL ScShutdownSystem, 1
$SYSCALL ScShutdownWorkerFactory, 2
$SYSCALL ScSignalAndWaitForSingleObject, 4
$SYSCALL ScSinglePhaseReject, 2
$SYSCALL ScStartProfile, 1
$SYSCALL ScStopProfile, 1
$SYSCALL ScSubmitIoRing, 4
$SYSCALL ScSubscribeWnfStateChange, 4
$SYSCALL ScSuspendProcess, 1
$SYSCALL ScSuspendThread, 2
$SYSCALL ScSystemDebugControl, 6
$SYSCALL ScTerminateEnclave, 2
$SYSCALL ScTerminateJobObject, 2
$SYSCALL ScTerminateProcess, 2
$SYSCALL ScTerminateThread, 2
$SYSCALL ScTestAlert, 0
$SYSCALL ScThawRegistry, 0
$SYSCALL ScThawTransactions, 0
$SYSCALL ScTraceControl, 6
$SYSCALL ScTraceEvent, 4
$SYSCALL ScTranslateFilePath, 4
$SYSCALL ScUmsThreadYield, 1
$SYSCALL ScUnloadDriver, 1
$SYSCALL ScUnloadKey, 1
$SYSCALL ScUnloadKey2, 2
$SYSCALL ScUnloadKeyEx, 2
$SYSCALL ScUnlockFile, 5
$SYSCALL ScUnlockVirtualMemory, 4
$SYSCALL ScUnmapViewOfSection, 2
$SYSCALL ScUnmapViewOfSectionEx, 3
$SYSCALL ScUnsubscribeWnfStateChange, 1
$SYSCALL ScUpdateWnfStateData, 7
$SYSCALL ScVdmControl, 2
$SYSCALL ScWaitForAlertByThreadId, 2
$SYSCALL ScWaitForDebugEvent, 4
$SYSCALL ScWaitForKeyedEvent, 4
$SYSCALL ScWaitForMultipleObjects, 5
$SYSCALL ScWaitForMultipleObjects32, 5
$SYSCALL ScWaitForSingleObject, 3
$SYSCALL ScWaitForWorkViaWorkerFactory, 5
$SYSCALL ScWaitHighEventPair, 1
$SYSCALL ScWaitLowEventPair, 1
$SYSCALL ScWorkerFactoryWorkerReady, 1
$SYSCALL ScWriteFile, 9
$SYSCALL ScWriteFileGather, 9
$SYSCALL ScWriteRequestData, 6
$SYSCALL ScWriteVirtualMemory, 5
$SYSCALL ScYieldExecution, 0
$SYSCALL ScUserAttachThreadInput, 3
$SYSCALL ScUserBeginPaint, 2
$SYSCALL ScUserBlockInput, 1
$SYSCALL ScUserFindWindowEx, 5
$SYSCALL ScUserBuildHwndList, 8
$SYSCALL ScUserBuildNameList, 4
$SYSCALL ScUserBuildPropList, 4
$SYSCALL ScUserCanCurrentThreadChangeForeground, 0
$SYSCALL ScUserCalculatePopupWindowPosition, 5
$SYSCALL ScUserCheckAccessForIntegrityLevel, 3
$SYSCALL ScUserCheckProcessForClipboardAccess, 2
$SYSCALL ScUserCloseWindowStation, 1
$SYSCALL ScUserDisableProcessWindowsGhosting, 0
$SYSCALL ScUserConsoleControl, 3
$SYSCALL ScUserCreateWindowStation, 8
$SYSCALL ScUserGetClassName, 3
$SYSCALL ScUserGetForegroundWindow, 0
$SYSCALL ScUserGetIconInfo, 6
$SYSCALL ScUserGetIconSize, 4
$SYSCALL ScUserGetProcessWindowStation, 0
$SYSCALL ScUserGetThreadState, 1
$SYSCALL ScUserGhostWindowFromHungWindow, 1
$SYSCALL ScUserHungWindowFromGhostWindow, 1
$SYSCALL ScUserInternalGetWindowText, 3
$SYSCALL ScUserInternalGetWindowIcon, 2
$SYSCALL ScUserOpenDesktop, 3
$SYSCALL ScUserOpenWindowStation, 2
$SYSCALL ScUserQueryWindow, 2
$SYSCALL ScUserSetActiveWindow, 1
$SYSCALL ScUserSetMessageExtraInfo, 1
$SYSCALL ScUserSetChildWindowNoActivate, 1
$SYSCALL ScUserSetFocus, 1
$SYSCALL ScUserSetInformationThread, 4
$SYSCALL ScUserSetProcessWindowStation, 1
$SYSCALL ScUserSetWindowPlacement, 2
$SYSCALL ScUserSetWindowStationUser, 4
$SYSCALL ScUserTestForInteractiveUser, 1
$SYSCALL ScUserSwitchDesktop, 3
$SYSCALL ScUserSetThreadDesktop, 1
$SYSCALL ScUserChildWindowFromPointEx, 4
$SYSCALL ScUserClipCursor, 1
$SYSCALL ScUserCloseDesktop, 1
$SYSCALL ScUserCopyAcceleratorTable, 3
$SYSCALL ScUserCreateAcceleratorTable, 2
$SYSCALL ScUserDeleteMenu, 3
$SYSCALL ScUserDestroyMenu, 1
$SYSCALL ScUserDestroyWindow, 1
$SYSCALL ScUserDragDetect, 3
$SYSCALL ScUserDragObject, 5
$SYSCALL ScUserDrawAnimatedRects, 4
$SYSCALL ScUserEndMenu, 0
$SYSCALL ScUserEndPaint, 2
$SYSCALL ScUserEnumDisplayMonitors, 4
$SYSCALL ScUserExcludeUpdateRgn, 2
$SYSCALL ScUserFlashWindowEx, 1
$SYSCALL ScUserGetAncestor, 2
$SYSCALL ScUserGetCaretBlinkTime, 0
$SYSCALL ScUserGetCaretPos, 1
$SYSCALL ScUserGetClipCursor, 1
$SYSCALL ScUserGetComboBoxInfo, 2
$SYSCALL ScUserGetCurrentInputMessageSource, 1
$SYSCALL ScUserGetCursor, 0
$SYSCALL ScUserGetCursorInfo, 1
$SYSCALL ScUserGetDCEx, 3
$SYSCALL ScUserGetDisplayAutoRotationPreferences, 1
$SYSCALL ScUserGetDoubleClickTime, 0
$SYSCALL ScUserGetGUIThreadInfo, 2
$SYSCALL ScUserGetGuiResources, 2
$SYSCALL ScUserGetLayeredWindowAttributes, 4
$SYSCALL ScUserGetListBoxInfo, 1
$SYSCALL ScUserGetMenuBarInfo, 4
$SYSCALL ScUserGetMenuItemRect, 4
$SYSCALL ScUserGetMouseMovePointsEx, 5
$SYSCALL ScUserGetRawInputData, 5
$SYSCALL ScUserGetRawInputDeviceList, 3
$SYSCALL ScUserGetRegisteredRawInputDevices, 3
$SYSCALL ScUserGetSendMessageReceiver, 1
$SYSCALL ScUserGetSystemMenu, 2
$SYSCALL ScUserGetThreadDesktop, 1
$SYSCALL ScUserGetTitleBarInfo, 2
$SYSCALL ScUserGetObjectInformation, 5
$SYSCALL ScUserGetWindowDC, 1
$SYSCALL ScUserGetWindowPlacement, 2
$SYSCALL ScUserHiliteMenuItem, 4
$SYSCALL ScUserInvalidateRect, 3
$SYSCALL ScUserInvalidateRgn, 3
$SYSCALL ScUserIsTouchWindow, 2
$SYSCALL ScUserKillTimer, 2
$SYSCALL ScUserLockWorkStation, 0
$SYSCALL ScUserLogicalToPhysicalPoint, 2
$SYSCALL ScUserMenuItemFromPoint, 4
$SYSCALL ScUserMoveWindow, 6
$SYSCALL ScUserOpenInputDesktop, 3
$SYSCALL ScUserPhysicalToLogicalPoint, 2
$SYSCALL ScUserPrintWindow, 3
$SYSCALL ScUserQueryInformationThread, 4
$SYSCALL ScUserRaiseLowerShellWindow, 2
$SYSCALL ScUserRedrawWindow, 4
$SYSCALL ScUserRealChildWindowFromPoint, 3
$SYSCALL ScUserRegisterHotKey, 4
$SYSCALL ScUserRemoveMenu, 3
$SYSCALL ScUserSendInput, 3
$SYSCALL ScUserSetCapture, 1
$SYSCALL ScUserSetTimer, 5
$SYSCALL ScUserSetClassWord, 3
$SYSCALL ScUserSetCursorPos, 2
$SYSCALL ScUserSetLayeredWindowAttributes, 4
$SYSCALL ScUserSetProcessRestrictionExemption, 1
$SYSCALL ScUserSetWindowPos, 7
$SYSCALL ScUserSetWindowWord, 3
$SYSCALL ScUserSetForegroundWindowForApplication, 1
$SYSCALL ScUserShellForegroundBoostProcess, 2
$SYSCALL ScUserSetAdditionalForegroundBoostProcesses, 1
$SYSCALL ScUserSetAdditionalPowerThrottlingProcess, 1
$SYSCALL ScUserShowCursor, 1
$SYSCALL ScUserShowWindow, 2
$SYSCALL ScUserShowWindowAsync, 2
$SYSCALL ScUserShutdownBlockReasonQuery, 3
$SYSCALL ScUserShutdownReasonDestroy, 1
$SYSCALL ScUserTrackMouseEvent, 1
$SYSCALL ScUserTrackPopupMenuEx, 6
$SYSCALL ScUserUnhookWinEvent, 1
$SYSCALL ScUserUnregisterHotKey, 2
$SYSCALL ScUserUserHandleGrantAccess, 3
$SYSCALL ScUserValidateRect, 2
$SYSCALL ScUserWindowFromDC, 1
$SYSCALL ScUserWindowFromPhysicalPoint, 2
$SYSCALL ScUserWindowFromPoint, 2

ScCode ENDS

END
