name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .\Source\KNSoft.Syscall.sln

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        platform: [x64, x86]
        config: [Debug, Release]
      fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Source checkout
      uses: actions/checkout@main
      with:
          submodules: recursive
    - name: Prepare MSBuild
      uses: microsoft/setup-msbuild@main
    - name: Restore nuget packages
      run: msbuild ${{env.SOLUTION_FILE_PATH}} -t:Restore -p:RestorePackagesConfig=true
    - name: Generate thunk data
      run: dotnet run .\Source --no-launch-profile --project .\Source\ThunkGenerator\ThunkGenerator.csproj
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Configuration=${{matrix.config}} /p:Platform=${{matrix.platform}}
    - name: Run unit test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: .\Source\OutDir\${{matrix.platform}}\${{matrix.config}}\UnitTest.exe
